name: Run Laravel Migration to Supabase

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      APP_NAME: "DH Motorsport"
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: ${{ secrets.APP_KEY }}

      DB_CONNECTION: pgsql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

      SESSION_DRIVER: cookie
      CACHE_DRIVER: array
      CACHE_STORE: array
      QUEUE_CONNECTION: sync
      LOG_CHANNEL: stderr
      VIEW_COMPILED_PATH: /tmp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql, pgsql, mbstring, dom, fileinfo, openssl, tokenizer, xml, ctype, json
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Clear Laravel config
        run: php artisan config:clear

      - name: Run migrations and seeders
        run: php artisan migrate --seed --force